### ISSUE TITLE
Package installation fails on linux environment

### ISSUE THREAD

**Issue by shashidhar26** [ThomasBury/geomapviz#1]
I am not sure if this package is designed for use in linux environments. But i did a simple 
pip install geomapviz -U

on my azure environment (docker running on linux). It fails with an error: 
`Building wheels for collected packages: cartopy
  Building wheel for cartopy (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/jovyan/envs/tacolight/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sk2ibzss/cartopy_9244987cf4b54e6fba3f7704fed08818/setup.py'"'"'; __file__='"'"'/tmp/pip-install-sk2ibzss/cartopy_9244987cf4b54e6fba3f7704fed08818/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-8i2d_iie
       cwd: /tmp/pip-install-sk2ibzss/cartopy_9244987cf4b54e6fba3f7704fed08818/`

Is this a known issue?

**Comment by ThomasBury** [comment]
This is a `cartopy` installation error. Try to install first from pre-built binaries `conda install -c conda-forge cartopy`. For installing on Linux platform, some dependencies are required, see [the cartopy documentation](https://scitools.org.uk/cartopy/docs/latest/installing.html) for details.

**Comment by shashidhar26** [comment]
Installation seems to work after a clean cartopy installation on both windows and gdp envs. So, this can be closed.
